// assets/src/Component/Header.jsx

const Header = () => {
	return (
		<div className="bg-blue-900 w-full">
			<div className="container mx-auto px-4 py-4">
				<span className="text-2xl font-light text-white uppercase tracking-widest mr-3"><strong className="font-bold">Aavoya</strong> Request a Quote</span>
			</div>
		</div>
	);
}

export default Header;

// assets/src/Components/Header.vue
<template>
	<div class="w-full bg-blue-800 px-5">
		<div class="container mx-auto">
			<div class="flex md:flex-row md:h-28 justify-start items-center">
				<div class="w-full ">
					<h1 class="text-white text-2xl tracking-tight uppercase"><span class="font-semibold">Aavoya</span> <span class="font-light">Request a Quote</span></h1>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
export default {
	name:'Header'
}
</script>
